### 1.-Crea un array de 10 números aleatorios enteros entre 0 y 100.

In [22]:
import numpy as np

aletario_num = np.random.randint(1, 101, 10)
print("Numero random de 0 a 100: ")
print(aletario_num)

Numero random de 0 a 100: 
[58 93 77 80  8 73 67 23 29 97]


### 2.-Crea un array de 5 números aleatorios decimales entre 0 y 1.

In [23]:
aletario_dec = np.random.rand(5)
print("Numero random de 0 a 1: ")
print(aletario_dec)

Numero random de 0 a 1: 
[0.50687891 0.78690863 0.07783955 0.97719664 0.1086646 ]


### 3.-Crea dos arrays de números aleatorios enteros de longitud 5 y concaténalos.

In [27]:
aleatorio1 = np.random.randint(0, 101, 5)
aleatorio2 = np.random.randint(0, 10, 5)
conexion = np.concatenate((aleatorio1, aleatorio2))
print("2 array longitud 5 conectados")
print(conexion)

2 array longitud 5 conectados
[99 21 40 63 70  8  6  5  0  0]


### 4.-Crea un array de 10 números aleatorios enteros y sepáralo en dos arrays de 5 elementos cada uno.

In [29]:
a=np.array(np.random.randint(1,20,10))
print("10 aleatorios en 2 arrays:")
print(np.split(a,2))


10 aleatorios en 2 arrays:
[array([17, 16, 10, 11, 18], dtype=int32), array([15, 15,  8,  6,  3], dtype=int32)]


### 5.-Crea una matriz de 3x3 con números aleatorios decimales entre 0 y 1.

In [30]:
print(np.array(np.random.rand(3,3)))

[[0.1547041  0.58401669 0.45414455]
 [0.21131176 0.51782361 0.42783165]
 [0.69787448 0.0670207  0.07188241]]


### 6.-Crea un array de 10 números aleatorios enteros y selecciona 3 elementos al azar.

In [32]:
a=np.array(np.random.randint(1,20,10))
print(f"Elementos seleccionados al azar: {np.random.choice(a,3)}")

Elementos seleccionados al azar: [11 11 10]


### 7.-Crea un array de 10 números aleatorios enteros entre 0 y 100 y calcula la media.

In [ ]:
a=np.array(np.random.randint(0,100,10))
print(f"Media: {np.mean(a)}")